### ISSUE TITLE
hydrate tsv file ISSUE

### ISSUE THREAD

**Issue by ShoZhou** [thepanacealab/SMMT#11]
When i try to use get_metadata.py to hydrate tsv file, the result is empty. Why and what can i do to get the resuly? Grateful for your answer. Many thanks

**Comment by jmbanda** [comment]
One of the many issues that could happen is that you might not have your Twitter API credentials properly configured. Can you confirm these are in place?

**Comment by ShoZhou** [comment]
> One of the many issues that could happen is that you might not have your Twitter API credentials properly configured. Can you confirm these are in place?

I'll try later, many thanks.

**Comment by tobischiebel** [comment]
Check #20, your tweepy version may be to new, consider downgrading it to 3.8.0 with e.g. `pip install --upgrade tweepy==3.8.0`
