### ISSUE TITLE
Get empty output files after hydration

### ISSUE THREAD

**Issue by LLY0203** [thepanacealab/SMMT#20]
Hello,

I was trying to use get_metadata.py to hydrate the CSV file. I got four output files but they are all empty. It seems that my Twitter API credentials are valid as shown in the screenshot below but the program stopped at the first 100 rows. Does anyone know the possible reason for this issue? Thanks in advance!
![image](https://user-images.githubusercontent.com/33755381/141777133-07985597-2ee5-4035-b29e-3997d3b1fa4a.png)

**Comment by tobischiebel** [comment]
Experiencing the exact same issue. Seems like the state of get_metadata.py has some conflicts with newer versions of some dependencies: `from tweepy import TweepError` is working no longer, also in line 54 the tweepy API call has an unexpected argument (wait_on_rate_limit_notify=True): `api = tweepy.API(auth, wait_on_rate_limit=True, retry_delay=60*3, retry_count=5,retry_errors=set([401, 404, 500, 503]), wait_on_rate_limit_notify=True)`

I removed both the import and the argument, which leads to the result above.

EDIT: Downgrading the tweepy module to 3.8.0 works fine. Use e.g. `pip install --upgrade tweepy==3.8.0`
